print("Olá Mundo")
print("---------------------------------------------------------------------------------------------------")
print("Anotações sobre o Python")
print("---------------------------------------------------------------------------------------------------")
print("input = É um comando como o "'Leia (Variavel)'" do portugol onde se escreve na mesma linha que a usa.")
print("Em outras palavras, um comando para poder dar entrada de dados ou informações ao programa.")
print("   Exemplo: 'nome= input (Digite seu nome: )'")
print("   Nesse exemplo, se colocasse isso num programa Python, poderei escrever algo")
print("\nfloat = Variavel de n° reais")
print("\nint = Variavel de nº inteiros")
print("\n'f' = Comando usado para referir uma variavel de maneira mais rapida. Geralmente, quando for referida, usar '{'}'")
print("\nif = Se")
print("\nif not = Se não(Caso contrario)")
print("\nelse = Senão")
print("\nelif = Senão se")
print("\nprint = Escreva")
print("'==' = Igual comparativo")
print("':' = Substituição das chaves do Portugol ou seja, blocos de comando.")
print("---------------------------------------------------------------------------------------------------")